version: 0.2

env:
  variables:
    REGION: ap-southeast-2
phases:
  install:
    commands:
      - npm install
      - pip install awscli --target=./lib
  build:
    commands:
      - sh ./scripts/deploy.sh
