Parameters:
  Stage:
    Type: String
  SourceRepository:
    Type: String


Resources:
  CLAWSCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "claws-codebuild-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "lambda:*"
                Resource: "*"
              -
                Effect: "Deny"
                Action:
                  - "lambda:Invoke*"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:*"
                Resource: "*"
              -
                Effect: "Deny"
                Action:
                  - "cloudformation:Delete*"
                  - "cloudformation:CancelUpdateStack"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLog*"
                  - "logs:Describe*"
                  - "logs:DeleteLog*"
                  - "logs:PutLogEvents"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "events:*"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:GetRole*"
                  - "iam:ListRoles"
                  - "iam:ListRolePolicies"
                  - "iam:PutRolePolicy"
                  - "iam:UpdateAssumeRolePolicy"
                  - "iam:PassRole"
                  - "iam:AttachRolePolicy"
                  - "iam:DetachRolePolicy"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "s3:CreateBucket"
                  - "s3:GetBucket*"
                  - "s3:GetObject*"
                  - "s3:ListBucket*"
                  - "s3:PutObject*"
                  - "s3:DeleteObject*"
                Resource: '*'

  CLAWSDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Name: claws-deploy
      Description: CodeBuild project for CLAWS.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: STAGE
            Value: !Ref Stage
      Source:
        Location: !Ref SourceRepository
        Type: github
      ServiceRole: !Ref CLAWSCodeBuildRole
